### PR TITLE
Add night mode to display settings

### PR DESCRIPTION
**Pull request by PaulSonOfLars**
should add link to night mode in display settings.

### CODE REVIEW

**Comment by xdevs23** [comment]
Dude night mode is directly over your addition... just commented out lol

**Comment by xdevs23** [comment]
Not working at all. LOL

**Comment by aviraxp** [comment]
@xdevs23 😂😂😂

**Comment by MSF-Jarvis** [comment]
@aviraxp

**Comment by MSF-Jarvis** [comment]
It's already there carnts

**Pull request closed without merging**
